manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com
    - name: dhruvinsh
      url-base: https://github.com
  projects:
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
  self:
    path: config
